services:
  mysql:
    container_name: mysql-sql-bsn
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Root
      MYSQLDATA: /var/lib/mysql/data
      MYSQL_DB : book_social_network
    volumes:
      - mysql:/data/mysql
    ports:
      - "3366:3306"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025



networks:
  spring-demo:
    driver: bridge




volumes:
  mysql:
    driver: local
