spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password: Root
    driver-class-name: org.mysql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQlDialect


  mail:
    host: localhost
    port: 1025
    username: preetham
    password: preetham
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 1996C6BBB8626B5F65E5E38FDFEC8
      expiration: 8640000